import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'locator.config.dart';
import 'package:dental_link_dashboard/features/admin/presentation/cubit/profile/profile_cubit.dart';
import 'package:dental_link_dashboard/core/auth/user_role_cubit.dart';

final locator = GetIt.instance;

@InjectableInit()
Future<void> configureDependencies() async {
  await locator.init();

  // Manual registrations for types not generated by injectable
  locator.registerSingleton<UserRoleCubit>(UserRoleCubit());
  locator.registerFactory<ProfileCubit>(() => ProfileCubit());
}
