// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWR5_uLD3rYSeglGYOvE-KJ6nmxSehUY',
    appId: '1:22318488604:web:2272b4c403cfd433bf93d9',
    messagingSenderId: '22318488604',
    projectId: 'dentallink-5440a',
    authDomain: 'dentallink-5440a.firebaseapp.com',
    storageBucket: 'dentallink-5440a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW9OldBIpiCsVHk7WTmWzZv5XC182MKoM',
    appId: '1:22318488604:android:3b17eb2898533c78bf93d9',
    messagingSenderId: '22318488604',
    projectId: 'dentallink-5440a',
    storageBucket: 'dentallink-5440a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJSKWtsOWplnNYEgonR77mJ1NiAfjMXU4',
    appId: '1:22318488604:ios:d0ef6802a1e80627bf93d9',
    messagingSenderId: '22318488604',
    projectId: 'dentallink-5440a',
    storageBucket: 'dentallink-5440a.firebasestorage.app',
    iosBundleId: 'com.example.dentalLinkDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJSKWtsOWplnNYEgonR77mJ1NiAfjMXU4',
    appId: '1:22318488604:ios:d0ef6802a1e80627bf93d9',
    messagingSenderId: '22318488604',
    projectId: 'dentallink-5440a',
    storageBucket: 'dentallink-5440a.firebasestorage.app',
    iosBundleId: 'com.example.dentalLinkDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUWR5_uLD3rYSeglGYOvE-KJ6nmxSehUY',
    appId: '1:22318488604:web:0719f3fb0ee8d46abf93d9',
    messagingSenderId: '22318488604',
    projectId: 'dentallink-5440a',
    authDomain: 'dentallink-5440a.firebaseapp.com',
    storageBucket: 'dentallink-5440a.firebasestorage.app',
  );
}
